# Generated by Django 3.2.3 on 2021-07-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0008_auto_20210708_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='hora_entrega',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
