# Generated by Django 3.2.3 on 2021-07-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0009_arriendo_hora_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='comentarios',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='hora_entrega',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
