# Generated by Django 3.2.3 on 2021-07-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0010_auto_20210708_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
