# Generated by Django 3.2.3 on 2021-07-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0011_alter_arriendo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='tipobici',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
