# Generated by Django 3.2.3 on 2021-07-09 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0012_arriendo_tipobici'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reperacion',
            fields=[
                ('id_auto_inc', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('foto', models.ImageField(upload_to='media/reparacion')),
                ('fecha_salida', models.DateField(null=True)),
                ('detalle_cliente', models.TextField(null=True)),
                ('Detalle_tecnico', models.TextField(null=True)),
                ('precio', models.IntegerField(null=True)),
                ('ingreso', models.BooleanField(default=False)),
                ('en_reparacion', models.BooleanField(default=False)),
                ('entregada', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BS.categoria')),
            ],
        ),
    ]
