# Generated by Django 3.2.3 on 2021-07-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0013_reperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='hora',
            field=models.DateTimeField(null=True),
        ),
    ]
