# Generated by Django 3.2.3 on 2021-07-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0014_arriendo_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arriendo',
            old_name='hora',
            new_name='fechaentrega',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='hora_entrega',
        ),
        migrations.AddField(
            model_name='arriendo',
            name='fechaarriendo',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='fecharetiro',
            field=models.DateTimeField(null=True),
        ),
    ]
