# Generated by Django 3.2.3 on 2021-07-10 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0015_auto_20210709_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arriendo',
            old_name='fechaarriendo',
            new_name='fecha_arriendo',
        ),
    ]
