# Generated by Django 3.2.3 on 2021-07-10 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0016_rename_fechaarriendo_arriendo_fecha_arriendo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reperacion',
            new_name='Reparacion',
        ),
    ]
