# Generated by Django 3.2.3 on 2021-07-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0018_alter_reparacion_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='foto',
            field=models.ImageField(null=True, upload_to='media/reparacion'),
        ),
    ]
